version: "3.4"
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.2"
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - node.name=test_sf5
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
  php:
    depends_on:
      - mysql
      - elastic
    build:
      context: ./docker/php
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: test-sf5-php
    volumes:
      - ./symfony:/srv/app
  mysql:
    image: "mysql:latest"
    container_name: test-sf5-mysql
    ports:
      - 33006:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-sf5
      MYSQL_USER: test-sf5
      MYSQL_PASSWORD: test-sf5
  nginx:
    image: "nginx:stable-alpine"
    depends_on:
      - php
    container_name: test-sf5-nginx
    ports:
      - 8080:80
    volumes:
      - ./symfony:/srv/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
