Address:
  type: object
  config:
    fields:
      id:
        type: 'Int!'
      street:
        type: 'String!'
      streetBis:
        type: 'String!'
      zipCode:
        type: 'String!'
      city:
        type: 'String!'
      state:
        type: 'String!'
      country:
        type: 'String!'
