Query:
  type: object
  config:
    fields:
      User:
        type: 'User'
        args:
          id:
            description: 'Resolves User using its id.'
            type: 'Int!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::getUser", [info, args["id"]])'
      Users:
        type: '[User]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::getUsers", [info])'
