User:
  type: object
  config:
    fields:
      id:
        type: 'Int!'
      firstName:
        type: 'String!'
      lastName:
        type: 'String!'
      sex:
        type: 'Int!'
      birthDateFormated:
        type: 'String!'
      addresses:
        type: '[Address]'
